name : a node build

on:
  push:

jobs:
  print1:
    runs-on: windows-latest

    steps:
      -
        run: echo "Hello automation"
  print2:
    runs-on: ubuntu-latest

    steps:
      - name: different operating system
        run: echo "This system output is from ubuntu"
  